"""
Seed areda-product-catalogs Firestore database with Visconti product data.
Uses google-cloud-firestore Python SDK with ADC.

Usage: python scripts/seed_firestore.py
"""

from google.cloud.firestore_v1 import Client
from datetime import datetime, timezone
import json

db = Client(project="ai-agents-go", database="areda-product-catalogs")
now = datetime.now(timezone.utc).isoformat()

PRODUCTS = [
    {
        "productCode": "VIS16-NY-610A",
        "brand": "VISCONTI",
        "style": "Classic",
        "styleCn": "\u7ecf\u5178\u5355\u6905",
        "name": "Niya Dining Chair",
        "nameCn": "\u9910\u6905 \u5c3c\u5a05",
        "model": "VIS16-NY-610A",
        "dimensions": "W610 \u00d7 D600 \u00d7 H790 mm",
        "material": "Walnut frame (N-series), Fabric/Faux leather upholstery",
        "materialCn": "\u6846\u67b6\u6750\u8d28 N\u7cfb\u5217 \u80e1\u6843, \u4e3b\u4f53\u6750\u8d28 fabric/fake leather",
        "features": "Solid wood frame, ergonomic backrest",
        "featuresCn": "\u5b9e\u6728\u6846\u67b6\uff0c\u4eba\u4f53\u5de5\u5b66\u9760\u80cc",
        "category": "dining-chairs",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 618.55,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 6,
        "leadTimeDays": 60,
        "collection": "Visconti Classic",
        "tags": ["walnut", "dining", "classic", "fabric"],
        "visible": True,
    },
    {
        "productCode": "VIS16-NY-610A-ASH",
        "brand": "VISCONTI",
        "style": "Classic",
        "styleCn": "\u7ecf\u5178\u5355\u6905",
        "name": "Niya Dining Chair (Ash)",
        "nameCn": "\u9910\u6905 \u5c3c\u5a05 (\u767d\u8721\u6728)",
        "model": "VIS16-NY-610A",
        "dimensions": "W610 \u00d7 D600 \u00d7 H790 mm",
        "material": "Ash wood frame (smoked), FAB.2 CA01 upholstery",
        "materialCn": "\u6846\u67b6\u6750\u8d28 N\u7cfb\u5217 \u767d\u8721 \u718f\u5496\u767d\u8721, \u4e3b\u4f53\u6750\u8d28 FAB.2 CA01",
        "features": "Solid wood frame, ergonomic backrest",
        "featuresCn": "\u5b9e\u6728\u6846\u67b6\uff0c\u4eba\u4f53\u5de5\u5b66\u9760\u80cc",
        "category": "dining-chairs",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 401.9,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 8,
        "leadTimeDays": 60,
        "collection": "Visconti Classic",
        "tags": ["ash", "dining", "classic", "fabric"],
        "visible": True,
    },
    {
        "productCode": "VIS23-LRE-940A",
        "brand": "VISCONTI",
        "style": "Modern",
        "styleCn": "\u73b0\u4ee3\u65f6\u5c1a",
        "name": "Laurel Lounge Chair",
        "nameCn": "\u4f11\u95f2\u6905 \u52b3\u745e\u5c14",
        "model": "VIS23-LRE-940A",
        "dimensions": "W940 \u00d7 D970 \u00d7 H750 mm",
        "material": "FAB.2 mid-century fabric, Black wood veneer shell",
        "materialCn": "\u4e3b\u4f53\u6750\u8d28 FAB.2 \u73b0\u4ee3\u4e2d\u53e4, \u6905\u5916\u58f3 \u6728\u76ae \u9ed1",
        "features": "360 degree swivel base",
        "featuresCn": "360\u00b0\u53ef\u65cb\u8f6c",
        "category": "lounge-chairs",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 701.6,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Modern",
        "tags": ["swivel", "lounge", "modern", "mid-century"],
        "visible": True,
    },
    {
        "productCode": "VIS23-RN-900A",
        "brand": "VISCONTI",
        "style": "Modern",
        "styleCn": "\u73b0\u4ee3\u65f6\u5c1a",
        "name": "Ryan Single Sofa",
        "nameCn": "\u5355\u4eba\u6c99\u53d1 \u745e\u6069",
        "model": "VIS23-RN-900A",
        "dimensions": "W900 \u00d7 D920 \u00d7 H980 mm",
        "material": "Litchi-grain leather shell, Fabric interior cushion",
        "materialCn": "\u5916\u58f3+\u5e95\u6846 \u8354\u679d\u7eb9 SODA, \u5185\u90e8+\u5750\u57ab+\u5934\u6795 Fabric",
        "features": "Mirror-finish stainless steel legs",
        "featuresCn": "\u955c\u9762\u4e0d\u9508\u94a2\u91d1\u5c5e\u817f",
        "category": "sofas",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 920.4,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Modern",
        "tags": ["leather", "sofa", "modern", "stainless-steel"],
        "visible": True,
    },
    {
        "productCode": "VIS23-DPX-1060A",
        "brand": "VISCONTI",
        "style": "Modern",
        "styleCn": "\u73b0\u4ee3\u65f6\u5c1a",
        "name": "Horizon Modular Sofa (Single)",
        "nameCn": "\u6a21\u5757\u6c99\u53d1 \u5730\u5e73\u7ebf",
        "model": "VIS23-DPX-1060A",
        "dimensions": "W1060 \u00d7 D1060 \u00d7 H650 mm",
        "material": "FAB.2 minimalist fabric base, FAB cushions",
        "materialCn": "\u5e95\u5ea7 FAB.2 \u73b0\u4ee3\u6781\u7b80, \u5750\u57ab+\u9760\u80cc+\u9760\u5305 FAB",
        "features": "Black matte metal legs, modular configuration",
        "featuresCn": "\u9ed1\u8272\u54d1\u5149\u6f06\u91d1\u5c5e\u817f",
        "category": "modular-sofas",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 782.6,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Modern",
        "tags": ["modular", "sofa", "modern", "minimalist"],
        "visible": True,
    },
    {
        "productCode": "VIS23-DPX-2360A-L",
        "brand": "VISCONTI",
        "style": "Modern",
        "styleCn": "\u73b0\u4ee3\u65f6\u5c1a",
        "name": "Horizon Modular Sofa (L-Shape)",
        "nameCn": "\u6a21\u5757\u6c99\u53d1 \u5730\u5e73\u7ebf L\u578b",
        "model": "VIS23-DPX-2360A-L",
        "dimensions": "W2360 \u00d7 D1060 \u00d7 H650 mm",
        "material": "FAB.2 minimalist fabric base, FAB cushions",
        "materialCn": "\u5e95\u5ea7 FAB.2 \u73b0\u4ee3\u6781\u7b80, \u5750\u57ab+\u9760\u80cc+\u9760\u5305 FAB",
        "features": "Black matte metal legs, L-shape configuration",
        "featuresCn": "\u9ed1\u8272\u54d1\u5149\u6f06\u91d1\u5c5e\u817f, L\u578b\u914d\u7f6e",
        "category": "modular-sofas",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0,
        "priceExwUsd": 1670.5,
        "priceFobUsd": 0,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Modern",
        "tags": ["modular", "sofa", "modern", "l-shape"],
        "visible": True,
    },
    {
        "productCode": "HW4-SZ001-V02",
        "brand": "VISCONTI",
        "style": "Hardware",
        "styleCn": "",
        "name": "SZ001 Hardware Unit V02",
        "nameCn": "",
        "model": "HW4-SZ001-V02",
        "dimensions": "",
        "material": "",
        "materialCn": "",
        "features": "",
        "featuresCn": "",
        "category": "accessories",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0.21406,
        "priceExwUsd": 0,
        "priceFobUsd": 175.6,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Accessories",
        "tags": ["hardware"],
        "visible": True,
    },
    {
        "productCode": "HW5-SD001-V01",
        "brand": "VISCONTI",
        "style": "Hardware",
        "styleCn": "",
        "name": "SD001 Hardware Unit V01",
        "nameCn": "",
        "model": "HW5-SD001-V01",
        "dimensions": "",
        "material": "",
        "materialCn": "",
        "features": "",
        "featuresCn": "",
        "category": "accessories",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0.053868,
        "priceExwUsd": 0,
        "priceFobUsd": 72.3,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Accessories",
        "tags": ["hardware"],
        "visible": True,
    },
    {
        "productCode": "HW1-S723",
        "brand": "VISCONTI",
        "style": "Kids",
        "styleCn": "",
        "name": "Doodle Chalkboard L120",
        "nameCn": "",
        "model": "HW1-S723",
        "dimensions": "150.4 x 9.3 x 1 cm",
        "material": "PE + plastic",
        "materialCn": "",
        "features": "Chalkboard surface, wall-mountable",
        "featuresCn": "",
        "category": "accessories",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0.11968,
        "priceExwUsd": 0,
        "priceFobUsd": 202.86,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Kids",
        "tags": ["kids", "chalkboard", "play"],
        "visible": True,
    },
    {
        "productCode": "HW1-S237",
        "brand": "VISCONTI",
        "style": "Kids",
        "styleCn": "",
        "name": "Balance Stumps Set of 12",
        "nameCn": "",
        "model": "HW1-S237",
        "dimensions": "dia 15 cm each",
        "material": "Wood",
        "materialCn": "",
        "features": "Set of 12 balance stumps",
        "featuresCn": "",
        "category": "accessories",
        "imageUrl": "",
        "galleryUrls": [],
        "volumeCbm": 0.163296,
        "priceExwUsd": 0,
        "priceFobUsd": 251.95,
        "currency": "USD",
        "moq": 1,
        "leadTimeDays": 60,
        "collection": "Visconti Kids",
        "tags": ["kids", "wood", "play", "balance"],
        "visible": True,
    },
]

batch = db.batch()

for p in PRODUCTS:
    p["createdAt"] = now
    p["updatedAt"] = now
    ref = db.collection("products").document()
    batch.set(ref, p)
    print(f"  + {p['productCode']}: {p['name']}")

# Catalog metadata
collections = list(set(p["collection"] for p in PRODUCTS))
categories = list(set(p["category"] for p in PRODUCTS))
meta_ref = db.collection("catalog-meta").document("visconti")
batch.set(meta_ref, {
    "name": "Visconti Furniture",
    "vendor": "Visconti",
    "totalProducts": len(PRODUCTS),
    "lastUpdated": now,
    "collections": collections,
    "categories": categories,
})

batch.commit()
print(f"\nSeeded {len(PRODUCTS)} products + catalog metadata to areda-product-catalogs")
print(f"Collections: {collections}")
print(f"Categories: {categories}")
